export enum ActionType {
    MOVIE_CAROUSEL_REQUEST = "MOVIE_CAROUSEL_REQUEST",
    MOVIE_CAROUSEL_SUCCESS = "MOVIE_CAROUSEL_SUCCESS",
    MOVIE_CAROUSEL_FAIL = "MOVIE_CAROUSEL_FAIL",
    
    MOVIE_TOP_RATED_REQUEST = "MOVIE_TOP_RATED_REQUEST",
    MOVIE_TOP_RATED_SUCCESS = "MOVIE_TOP_RATED_SUCCESS",
    MOVIE_TOP_RATED_FAIL = "MOVIE_TOP_RATED_FAIL",
    
    MOVIE_POPULAR_REQUEST = "MOVIE_POPULAR_REQUEST",
    MOVIE_POPULAR_SUCCESS = "MOVIE_POPULAR_SUCCESS",
    MOVIE_POPULAR_FAIL = "MOVIE_POPULAR_FAIL",

    MOVIE_DETAIL_REQUEST = "MOVIE_DETAIL_REQUEST",
    MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS",
    MOVIE_DETAIL_FAIL = "MOVIE_DETAIL_FAIL",

    SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST",
    SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS",
    SEARCH_MOVIE_FAIL = "SEARCH_MOVIE_FAIL",
}